name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        echo "IMG_TAG=$(date +%s)" >> $GITHUB_ENV
        docker build . --file Dockerfile --tag ghcr.io/budaizalan/webtest4azure:$IMG_TAG
        docker login ghcr.io -u budaizalan -p ${{secrets.GHCR_TOKEN}}
        docker push ghcr.io/budaizalan/webtest4azure:$IMG_TAG
