# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - teszt-budaizalan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f8812602369e4871a9e9e8d41b895d29 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b3ea0c769c70426fa2968740b0d3f56f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_f8812602369e4871a9e9e8d41b895d29 }}/budaizalan/webtest4azure:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'teszt-budaizalan'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3973efe1309c482088b9a08326089489 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_f8812602369e4871a9e9e8d41b895d29 }}/budaizalan/webtest4azure:${{ github.sha }}'